import './regression/knowledge-regression.test.mjs'
import './regression/workbench-regression.test.mjs'
import './regression/capture-overlay-regression.test.mjs'
import './regression/trade-detail-regression.test.mjs'
import './regression/period-review-regression.test.mjs'
import './regression/target-selector-regression.test.mjs'
import './regression/session-mainline-e2e.test.mjs'
